export const products = [
  {
    id: 1,
    name: "iPhone 15 Pro",
    price: 999,
    category: "Electrónica",
    description: "Chip A17 Pro, cámara de 48MP y pantalla Super Retina XDR de 6.1\".",
    image: "https://picsum.photos/seed/iphone15pro/300/300",
    rating: 4.8,
    reviews: 2341,
  },
  {
    id: 2,
    name: "MacBook Air M3",
    price: 1299,
    category: "Electrónica",
    description: "Chip M3, 8GB RAM, 256GB SSD. Ultradelgada y ligera.",
    image: "https://picsum.photos/seed/macbookair/300/300",
    rating: 4.9,
    reviews: 1876,
  },
  {
    id: 3,
    name: "Sony WH-1000XM5",
    price: 349,
    category: "Electrónica",
    description: "Auriculares con cancelación de ruido líder en la industria.",
    image: "https://picsum.photos/seed/sonyheadphones/300/300",
    rating: 4.7,
    reviews: 3102,
  },
  {
    id: 4,
    name: "Samsung Smart TV 55\"",
    price: 599,
    category: "Electrónica",
    description: "Pantalla 4K QLED con HDR y smart TV integrado.",
    image: "https://picsum.photos/seed/samsungtv55/300/300",
    rating: 4.6,
    reviews: 987,
  },
  {
    id: 5,
    name: "iPad Pro 12.9\"",
    price: 1099,
    category: "Electrónica",
    description: "Pantalla Liquid Retina XDR, chip M2, perfecto para creativos.",
    image: "https://picsum.photos/seed/ipadpro/300/300",
    rating: 4.8,
    reviews: 1543,
  },
  {
    id: 6,
    name: "Licuadora KitchenAid",
    price: 89,
    category: "Hogar",
    description: "5 velocidades, jarra de vidrio de 1.4L, motor de 550W.",
    image: "https://picsum.photos/seed/kitchenaid/300/300",
    rating: 4.5,
    reviews: 654,
  },
  {
    id: 7,
    name: "Cafetera Nespresso Vertuo",
    price: 149,
    category: "Hogar",
    description: "Sistema de cápsulas, 5 tamaños de café, calentamiento en 30 seg.",
    image: "https://picsum.photos/seed/nespresso/300/300",
    rating: 4.7,
    reviews: 2198,
  },
  {
    id: 8,
    name: "Robot Aspirador Roomba",
    price: 299,
    category: "Hogar",
    description: "Navegación inteligente, compatible con Alexa y Google Home.",
    image: "https://picsum.photos/seed/roomba/300/300",
    rating: 4.4,
    reviews: 876,
  },
  {
    id: 9,
    name: "Nike Air Max 270",
    price: 129,
    category: "Ropa",
    description: "Zapatillas con cámara de aire Max, diseño moderno y cómodo.",
    image: "https://picsum.photos/seed/nikeairmax/300/300",
    rating: 4.6,
    reviews: 3456,
  },
  {
    id: 10,
    name: "Levi's 501 Original",
    price: 69,
    category: "Ropa",
    description: "El clásico jean de corte recto, 100% algodón.",
    image: "https://picsum.photos/seed/levis501/300/300",
    rating: 4.5,
    reviews: 5678,
  },
  {
    id: 11,
    name: "Camiseta Premium Algodón",
    price: 29,
    category: "Ropa",
    description: "100% algodón orgánico, corte moderno, disponible en varios colores.",
    image: "https://picsum.photos/seed/tshirtbasic/300/300",
    rating: 4.3,
    reviews: 1234,
  },
  {
    id: 12,
    name: "Café Starbucks 1lb",
    price: 19,
    category: "Alimentos",
    description: "Café molido de tueste medio, granos de origen único.",
    image: "https://picsum.photos/seed/starbuckscoffee/300/300",
    rating: 4.6,
    reviews: 8921,
  },
  {
    id: 13,
    name: "Mix de Nueces Premium",
    price: 24,
    category: "Alimentos",
    description: "900g de almendras, nueces, anacardos y pistachos sin sal.",
    image: "https://picsum.photos/seed/mixednuts/300/300",
    rating: 4.7,
    reviews: 2345,
  },
  {
    id: 14,
    name: "Té Verde Orgánico",
    price: 14,
    category: "Alimentos",
    description: "50 bolsitas de té verde japonés Sencha, certificado orgánico.",
    image: "https://picsum.photos/seed/greentea/300/300",
    rating: 4.4,
    reviews: 1678,
  },
  {
    id: 15,
    name: "Mochila Samsonite 30L",
    price: 89,
    category: "Accesorios",
    description: "Mochila resistente al agua, compartimento para laptop de 15.6\".",
    image: "https://picsum.photos/seed/samsonitebackpack/300/300",
    rating: 4.5,
    reviews: 1102,
  },
];

export const categories = ["Todos", ...new Set(products.map((p) => p.category))];
